# Generated by Django 2.2.7 on 2019-11-19 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_auto_20191119_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='e_to',
            field=models.ForeignKey(blank=True, db_column='e_to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='adventure.Room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='n_to',
            field=models.ForeignKey(blank=True, db_column='n_to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='adventure.Room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='s_to',
            field=models.ForeignKey(blank=True, db_column='s_to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='adventure.Room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='w_to',
            field=models.ForeignKey(blank=True, db_column='w_to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='adventure.Room'),
        ),
    ]
