# Generated by Django 2.2.7 on 2019-11-20 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0003_auto_20191119_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='currentRoom',
            field=models.ForeignKey(blank=True, db_column='currentRoom', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='adventure.Room'),
        ),
    ]
